version: '3.8'
services:
  postgres:
    image: "postgres:14"
    env_file:
      - .env
    ports:
      - '127.0.0.1:50432:5432'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5050:80"